const SYNC_URL="https://script.google.com/macros/s/AKfycby5W9DL6iWgvW9bYFR3niMXnvB8cxDw4ELye1brVmAmW68jkqm42RTwYyqqzVLuZ50/exec";
const DEFAULTS={salary:19000,rent:5900,budget:17500,variable:{Groceries:2400,Transport:700,"Dining out":1100,Utilities:650,Personal:900,"Family support":1500},funds:{emergency:[24600,30000],tunisia:[20500,50000]},history:[["Mar",15800],["Apr",16900],["May",16200],["Jun",17400],["Jul",16800]],tx:[],docs:[],cards:[],plans:[],accounts:[{name:"CBQ Current",type:"bank",balance:15000},{name:"Cash Wallet",type:"cash",balance:2000}],loans:[],commitments:[],attention:[],review:{checks:{},keep:"",stop:"",start:"",change:""}};
const $=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x)),fmt=n=>"QAR "+Math.round(Number(n)||0).toLocaleString("en-US"),title=s=>String(s||"").replace(/[-_]/g," ").replace(/\b\w/g,m=>m.toUpperCase()),pretty=s=>{if(!s)return"—";const d=new Date(s+"T00:00:00");return isNaN(d)?s:d.toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"})},esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function load(){try{const d=JSON.parse(localStorage.getItem("azizData"));return d?{...clone(DEFAULTS),...d,variable:{...DEFAULTS.variable,...(d.variable||{})},funds:{...DEFAULTS.funds,...(d.funds||{})},review:{...DEFAULTS.review,...(d.review||{})},commitments:d.commitments||[]}:clone(DEFAULTS)}catch{return clone(DEFAULTS)}}
let DATA=load();
function persist(push=true){localStorage.setItem("azizData",JSON.stringify(DATA));if(push)syncPush(true)}
function getPass(){return localStorage.getItem("azizPass")||"aziz2026"}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2000)}
function unlock(){if($("pw").value.trim()!==getPass()){ $("err").textContent="Access denied";$("pw").value="";return }$("lock").style.opacity=0;setTimeout(()=>{$("lock").style.display="none";$("app").classList.add("live");render();syncPull()},300)}
function relock(){location.reload()}
$("pw").addEventListener("keydown",e=>{if(e.key==="Enter")unlock()});
function nav(page){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("on",x.id==="page-"+page));document.querySelectorAll("[data-page]").forEach(x=>x.classList.toggle("on",x.dataset.page===page));$("crumb").textContent=title(page);window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-page]").forEach(b=>b.addEventListener("click",()=>nav(b.dataset.page)));
function normalizeTx(t,i){if(Array.isArray(t))return{id:"legacy-"+i,desc:t[0]||"Transaction",amount:Number(t[1])||0,category:t[2]||"Other",date:t[3]||"",type:["income","deposit"].includes(t[4])?"income":"expense",account:DATA.accounts?.[0]?.name||"Primary"};return{id:t.id||"tx-"+i,...t,amount:Number(t.amount)||0}}
function txs(){return(DATA.tx||[]).map(normalizeTx)}
function funds(){return Object.entries(DATA.funds||{}).map(([key,v])=>Array.isArray(v)?{key,name:key,current:Number(v[0])||0,target:Number(v[1])||0,date:v[2]||""}:{key,name:v.name||key,current:Number(v.current)||0,target:Number(v.target)||0,date:v.date||""})}
function accountsTotal(){return(DATA.accounts||[]).reduce((s,a)=>s+(Number(a.balance)||0),0)}
function protectedTotal(){return funds().reduce((s,f)=>s+f.current,0)}
function debtTotal(){return(DATA.loans||[]).reduce((s,l)=>s+Math.max(0,(Number(l.total)||0)-(Number(l.paid)||0)),0)}
function netWorth(){return accountsTotal()+protectedTotal()-debtTotal()}
function monthStats(){const key=new Date().toISOString().slice(0,7),m=txs().filter(t=>(t.date||"").startsWith(key));return{income:m.filter(t=>t.type==="income").reduce((s,t)=>s+t.amount,0),expense:m.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amount,0)}}
function commitments(){const manual=(DATA.commitments||[]).map((c,i)=>typeof c==="string"?{id:"legacy-"+i,name:c,amount:0,date:"",type:"Other",paid:false}:{id:c.id||"c-"+i,paid:false,...c,amount:Number(c.amount)||0});const cheques=[];(DATA.loans||[]).forEach((l,li)=>(l.cheques||[]).forEach((c,ci)=>{if(!c.paid)cheques.push({id:`loan-${li}-${ci}`,name:`${l.name} cheque`,amount:Number(c.amount)||0,date:c.date||"",type:"Cheque",paid:false,linkedLoan:true})}));return[...manual,...cheques]}
function nextDays(days){const now=new Date();now.setHours(0,0,0,0);const end=new Date(now);end.setDate(end.getDate()+days);return commitments().filter(c=>{if(c.paid||!c.date)return false;const d=new Date(c.date+"T00:00:00");return d>=now&&d<=end})}
function safeSpend(){const m=monthStats(),ob=nextDays(30).reduce((s,c)=>s+c.amount,0),liquid=accountsTotal(),remaining=Math.max(0,(Number(DATA.budget)||0)-m.expense);return Math.max(0,liquid-ob-Math.min(remaining,liquid*.35))}
function render(){renderHeader();renderOverview();renderMoney();renderGoals();renderCommitments();renderVault();renderReview();renderSettings()}
function renderHeader(){const h=new Date().getHours();$("greeting").textContent=`Good ${h<12?"morning":h<18?"afternoon":"evening"}, Aziz.`;$("clock").textContent=new Date().toLocaleString("en-GB",{weekday:"short",day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}
function goalRow(f){const pct=Math.min(100,Math.round(f.current/(f.target||1)*100));return`<div class="goalRow"><div class="goalTop"><b>${title(f.name)}</b><span>${pct}%</span></div><div class="progress"><i style="width:${pct}%"></i></div><div class="goalMeta"><span>${fmt(f.current)}</span><span>${fmt(f.target)}</span></div></div>`}
function renderOverview(){const m=monthStats(),f=funds().sort((a,b)=>(b.current/b.target)-(a.current/a.target)),n30=nextDays(30),n30sum=n30.reduce((s,c)=>s+c.amount,0),usage=m.expense/(Number(DATA.budget)||1);$("netWorth").textContent=fmt(netWorth());$("safeSpend").textContent=fmt(safeSpend());$("protectedCapital").textContent=fmt(protectedTotal());$("next30").textContent=fmt(n30sum);$("next30sub").textContent=n30.length?`${n30.length} known commitment${n30.length>1?"s":""}`:"No dated commitments recorded";const pts=[[usage>.8?"Budget pressure":"Spending under control",`You have used ${Math.round(usage*100)}% of this month’s budget.`],["Closest funded goal",f[0]?`${title(f[0].name)} is ${Math.min(100,Math.round(f[0].current/f[0].target*100))}% funded.`:"Create a funded goal to start compounding progress."],[n30sum>accountsTotal()*.35?"Liquidity watch":"Liquidity runway",`Known 30-day commitments equal ${fmt(n30sum)} against ${fmt(accountsTotal())} in liquid accounts.`]];$("brief").innerHTML=pts.map((x,i)=>`<div class="briefItem"><div class="briefN">0${i+1}</div><div><b>${x[0]}</b><p>${x[1]}</p></div></div>`).join("");$("goalPreview").innerHTML=f.slice(0,4).map(goalRow).join("")||`<p class="sub">No goals yet.</p>`;let hist=(DATA.history||[]).slice(-5).map(x=>({label:x[0],out:Number(x[1])||0,income:Number(DATA.salary)||0}));hist.push({label:new Date().toLocaleString("en",{month:"short"}),out:m.expense,income:m.income||Number(DATA.salary)||0});const max=Math.max(1,...hist.flatMap(x=>[x.out,x.income]));$("chart").innerHTML=hist.map(x=>`<div class="barWrap"><i class="in" style="height:${Math.max(3,x.income/max*100)}%"></i><i class="out" style="height:${Math.max(3,x.out/max*100)}%"></i></div>`).join("");$("chartLabels").innerHTML=hist.map(x=>`<span>${x.label}</span>`).join("");let att=n30.slice(0,5).map(c=>[c.name,`${fmt(c.amount)} · due ${pretty(c.date)}`]);if(!att.length)att=(DATA.attention||[]).slice(0,5).map(x=>[x,"Manual attention item"]);if(!att.length)att=[["Clear runway","No urgent dated commitments are recorded."]];$("attention").innerHTML=att.map(x=>`<div class="attn"><span class="pin"></span><div><b>${esc(x[0])}</b><span>${x[1]}</span></div></div>`).join("")}
function renderMoney(){const m=monthStats();$("moneyNet").textContent=fmt(netWorth());$("liquid").textContent=fmt(accountsTotal());$("monthSpend").textContent=fmt(m.expense);$("budgetUsage").textContent=`${Math.round(m.expense/(Number(DATA.budget)||1)*100)}% of ${fmt(DATA.budget)} budget`;$("debtTotal").textContent=fmt(debtTotal());$("accounts").innerHTML=(DATA.accounts||[]).map((a,i)=>`<div class="accountRow"><div class="accountIcon">${(a.name||"A").split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div class="grow"><b>${esc(a.name)}</b><span>${title(a.type||"account")}</span></div><div class="amount">${fmt(a.balance)}</div><button class="btn" onclick="deleteAccount(${i})">×</button></div>`).join("")||`<p class="sub">Add your first account.</p>`;$("monthPosition").innerHTML=`<div class="goalRow"><div class="goalTop"><b>Income recorded</b><span>${fmt(m.income)}</span></div></div><div class="goalRow"><div class="goalTop"><b>Expenses recorded</b><span>${fmt(m.expense)}</span></div></div><div class="goalRow"><div class="goalTop"><b>Budget remaining</b><span>${fmt(Math.max(0,DATA.budget-m.expense))}</span></div></div><div class="goalRow"><div class="goalTop"><b>Net monthly cashflow</b><span class="${m.income-m.expense>=0?"green":"red"}">${fmt(m.income-m.expense)}</span></div></div>`;$("txTable").innerHTML=txs().slice().reverse().slice(0,30).map((t,ri)=>{const original=txs().length-1-ri;return`<tr><td><span class="pill ${t.type==="income"?"in":t.type==="transfer"?"gold":"out"}">${title(t.type)}</span></td><td>${esc(t.desc)}</td><td class="muted">${esc(t.account||"—")}</td><td class="muted">${esc(t.category||"—")}</td><td class="muted">${pretty(t.date)}</td><td class="${t.type==="income"?"green":t.type==="expense"?"red":"gold"}">${t.type==="income"?"+":t.type==="expense"?"−":""}${fmt(t.amount)}</td><td><button class="btn" onclick="deleteTx(${original})">×</button></td></tr>`}).join("")||`<tr><td colspan="7" class="muted">No transactions yet.</td></tr>`}
function renderGoals(){const f=funds();$("goalCards").innerHTML=f.map(x=>{const pct=Math.min(100,Math.round(x.current/(x.target||1)*100));return`<div class="card"><div class="cardTitle">Capital Goal <button class="btn" onclick="openGoal('${x.key}')">Edit</button></div><div class="metric">${title(x.name)}</div><div class="sub">${fmt(x.current)} of ${fmt(x.target)}${x.date?` · target ${pretty(x.date)}`:""}</div><div class="progress"><i style="width:${pct}%"></i></div><div class="goalMeta"><span>${pct}% funded</span><span>${fmt(Math.max(0,x.target-x.current))} left</span></div></div>`}).join("")||`<div class="card"><p class="sub">No goals yet.</p></div>`;$("plans").innerHTML=(DATA.plans||[]).map((p,i)=>`<div class="commitRow"><div class="accountIcon">${String(i+1).padStart(2,"0")}</div><div class="grow"><b>${esc(p[0])}</b><span>${p[1]?pretty(p[1]):"No target date"} · ${p[2]||"Planned"}</span></div><button class="btn" onclick="deletePlan(${i})">×</button></div>`).join("")||`<p class="sub">No long-range objectives yet.</p>`}
function renderCommitments(){const list=commitments().filter(c=>!c.paid).sort((a,b)=>(a.date||"9999").localeCompare(b.date||"9999"));$("commit30").textContent=fmt(nextDays(30).reduce((s,c)=>s+c.amount,0));$("commitDebt").textContent=fmt(debtTotal());$("rentMetric").textContent=fmt(DATA.rent);$("commitList").innerHTML=list.map(c=>`<div class="commitRow"><div class="accountIcon">${(c.type||"C")[0]}</div><div class="grow"><b>${esc(c.name)}</b><span>${c.type||"Commitment"}${c.date?` · ${pretty(c.date)}`:" · no date"}</span></div><div class="amount">${fmt(c.amount)}</div>${c.linkedLoan?"":`<button class="btn" onclick="markCommitment('${c.id}')">Paid</button>`}</div>`).join("")||`<p class="sub">No active commitments recorded.</p>`;$("loanList").innerHTML=(DATA.loans||[]).map((l,i)=>{const out=Math.max(0,(Number(l.total)||0)-(Number(l.paid)||0)),pct=Math.min(100,(Number(l.paid)||0)/(Number(l.total)||1)*100);return`<div class="goalRow"><div class="goalTop"><b>${esc(l.name||"Liability")}</b><span class="red">${fmt(out)} left</span></div><div class="progress"><i style="width:${pct}%"></i></div><div class="goalMeta"><span>${fmt(l.paid||0)} paid</span><button class="btn" onclick="payLoan(${i})">Record payment</button></div></div>`}).join("")||`<p class="sub">No liabilities recorded.</p>`}
function renderVault(){const now=new Date();$("docTable").innerHTML=(DATA.docs||[]).map(d=>{const exp=d[2]?new Date(d[2]+"T00:00:00"):null,days=exp?Math.ceil((exp-now)/86400000):9999,status=days<0?"Expired":days<90?"Renew soon":"Valid";return`<tr><td>${esc(d[0])}</td><td class="muted">•••• ${String(d[1]||"").slice(-4)}</td><td class="muted">${d[2]?pretty(d[2]):"—"}</td><td><span class="pill ${status==="Valid"?"in":status==="Renew soon"?"gold":"out"}">${status}</span></td></tr>`}).join("")||`<tr><td colspan="4" class="muted">No documents stored.</td></tr>`;$("cards").innerHTML=(DATA.cards||[]).map(c=>`<div class="card" style="margin-bottom:10px;background:linear-gradient(135deg,#1b1a18,#0c0c0d);border-color:rgba(200,170,110,.16)"><div class="cardTitle">Payment Card <span class="gold">AZIZ OS</span></div><div class="metric" style="font-size:17px;letter-spacing:2px">•••• •••• •••• ${String(c[2]||c[1]||"").slice(-4)}</div><div class="goalMeta" style="margin-top:15px"><span>${esc(c[0])}</span><span>${c[3]||""}</span></div></div>`).join("")||`<p class="sub">No cards stored.</p>`}
function renderReview(){const qs=["I know my current liquid cash position.","All commitments for the next 30 days are recorded.","I moved money toward at least one strategic goal.","My spending matched my priorities.","I made one decision that improves next month."],checks=DATA.review?.checks||{};$("reviewChecks").innerHTML=qs.map((q,i)=>`<label class="reviewQ"><input type="checkbox" data-review="${i}" ${checks[i]?"checked":""}><span>${q}</span></label>`).join("");$("rvKeep").value=DATA.review?.keep||"";$("rvStop").value=DATA.review?.stop||"";$("rvStart").value=DATA.review?.start||"";$("rvChange").value=DATA.review?.change||""}
function renderSettings(){$("setSalary").value=DATA.salary||0;$("setRent").value=DATA.rent||0;$("setBudget").value=DATA.budget||0;$("setCats").value=Object.keys(DATA.variable||{}).join(", ")}
function openModal(id){$(id).classList.add("open")}function closeModal(id){$(id).classList.remove("open")}
function openTx(){const cats=Object.keys(DATA.variable||{});$("txCat").innerHTML=cats.map(x=>`<option>${x}</option>`).join("")+`<option>Other</option>`;const opts=(DATA.accounts||[]).map((a,i)=>`<option value="${i}">${esc(a.name)}</option>`).join("");$("txAccount").innerHTML=opts;$("txTo").innerHTML=opts;$("txDate").value=new Date().toISOString().slice(0,10);$("txDesc").value="";$("txAmount").value="";openModal("txModal");toggleTransfer()}
$("txType").addEventListener("change",toggleTransfer);function toggleTransfer(){$("toWrap").style.display=$("txType").value==="transfer"?"block":"none"}
function saveTx(){const type=$("txType").value,amount=Number($("txAmount").value),desc=$("txDesc").value.trim(),from=Number($("txAccount").value),to=Number($("txTo").value);if(!amount||!desc||!DATA.accounts?.[from])return toast("Complete the transaction details");if(type==="expense")DATA.accounts[from].balance=Number(DATA.accounts[from].balance||0)-amount;if(type==="income")DATA.accounts[from].balance=Number(DATA.accounts[from].balance||0)+amount;if(type==="transfer"){if(from===to)return toast("Choose two different accounts");DATA.accounts[from].balance-=amount;DATA.accounts[to].balance=Number(DATA.accounts[to].balance||0)+amount}DATA.tx.push({id:"tx-"+Date.now(),desc,amount,category:$("txCat").value,date:$("txDate").value,type,account:DATA.accounts[from].name,toAccount:type==="transfer"?DATA.accounts[to].name:""});persist();closeModal("txModal");render();toast("Transaction recorded")}
function deleteTx(i){if(confirm("Delete this transaction? Account balances will not be reversed automatically.")){DATA.tx.splice(i,1);persist();render()}}
function saveAccount(){const name=$("accName").value.trim();if(!name)return toast("Account name required");DATA.accounts.push({name,type:$("accType").value,balance:Number($("accBalance").value)||0});persist();closeModal("accountModal");render();toast("Account added")}
function deleteAccount(i){if(confirm("Delete this account?")){DATA.accounts.splice(i,1);persist();render()}}
function openGoal(key=""){const f=funds().find(x=>x.key===key);$("goalKey").value=key;$("goalName").value=f?.name||"";$("goalCurrent").value=f?.current||"";$("goalTarget").value=f?.target||"";$("goalDate").value=f?.date?String(f.date).slice(0,10):"";$("goalModalTitle").textContent=key?"Edit Goal":"New Goal";openModal("goalModal")}
function saveGoal(){const old=$("goalKey").value,name=$("goalName").value.trim(),key=(name||"goal").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");if(!name||!Number($("goalTarget").value))return toast("Name and target required");DATA.funds[key]={name,current:Number($("goalCurrent").value)||0,target:Number($("goalTarget").value)||0,date:$("goalDate").value};if(old&&old!==key)delete DATA.funds[old];persist();closeModal("goalModal");render();toast("Goal updated")}
function addPlan(){const t=$("planTitle").value.trim();if(!t)return toast("Objective required");DATA.plans.push([t,$("planDate").value,"Planned"]);$("planTitle").value="";$("planDate").value="";persist();render()}
function deletePlan(i){DATA.plans.splice(i,1);persist();render()}
function openCommitment(){$("comName").value="";$("comAmount").value="";$("comDate").value="";openModal("commitModal")}
function saveCommitment(){const name=$("comName").value.trim();if(!name)return toast("Commitment name required");DATA.commitments.push({id:"c-"+Date.now(),name,amount:Number($("comAmount").value)||0,date:$("comDate").value,type:$("comType").value,paid:false});persist();closeModal("commitModal");render();toast("Commitment added")}
function markCommitment(id){const c=DATA.commitments.find(x=>x.id===id);if(c){c.paid=true;persist();render()}}
function addLoan(){const name=prompt("Liability name:");if(!name)return;const total=Number(prompt("Total amount:"));if(!total)return;DATA.loans.push({name,total,paid:0,cheques:[]});persist();render()}
function payLoan(i){const amt=Number(prompt("Payment amount:"));if(!amt)return;const l=DATA.loans[i];l.paid=Math.min(Number(l.total)||0,(Number(l.paid)||0)+amt);persist();render()}
function saveReview(){const checks={};document.querySelectorAll("[data-review]").forEach(x=>checks[x.dataset.review]=x.checked);DATA.review={checks,keep:$("rvKeep").value,stop:$("rvStop").value,start:$("rvStart").value,change:$("rvChange").value};persist();toast("CEO review saved")}
function saveSettings(){DATA.salary=Number($("setSalary").value)||0;DATA.rent=Number($("setRent").value)||0;DATA.budget=Number($("setBudget").value)||0;const n={};$("setCats").value.split(",").map(x=>x.trim()).filter(Boolean).forEach(k=>n[k]=DATA.variable?.[k]||1000);DATA.variable=n;persist();render();toast("Baseline saved")}
function changePass(){const p=$("newPass").value;if(p.length<6)return toast("Use at least 6 characters");localStorage.setItem("azizPass",p);$("newPass").value="";toast("Local password changed")}
function exportData(){const b=new Blob([JSON.stringify(DATA,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`aziz-os-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
$("restore").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{DATA={...clone(DEFAULTS),...JSON.parse(r.result)};persist(false);render();toast("Backup restored")}catch{toast("Invalid backup file")}};r.readAsText(f)});
function hardReset(){if(confirm("Factory reset all Aziz OS browser data?")){localStorage.removeItem("azizData");location.reload()}}
function syncPull(){if(!SYNC_URL)return;fetch(SYNC_URL,{mode:"cors"}).then(r=>r.json()).then(d=>{if(d&&d.salary){DATA={...clone(DEFAULTS),...d,variable:{...DEFAULTS.variable,...(d.variable||{})},funds:{...DEFAULTS.funds,...(d.funds||{})},commitments:d.commitments||[]};persist(false);render();$("systemStatus").textContent="System online · Google sync connected"}}).catch(()=>{})}
let syncTimer;function syncPush(silent=false){if(!SYNC_URL)return;clearTimeout(syncTimer);syncTimer=setTimeout(()=>fetch(SYNC_URL,{method:"POST",body:JSON.stringify(DATA),mode:"cors"}).then(()=>{if(!silent)toast("Google sync pushed")}).catch(()=>{if(!silent)toast("Sync unavailable — local data safe")}),silent?800:50)}
setInterval(()=>{if($("app").classList.contains("live"))renderHeader()},30000);
